import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  tr: {
    // Setup
    setup_title: 'Setup Wizard',
    setup_subtitle: 'Metin2 Dev Toolkit\'i yapılandırın',
    setup_db_title: 'MySQL Database',
    setup_db_desc: 'Metin2 veritabanı bağlantı ayarları',
    setup_ftp_title: 'FTP Server',
    setup_ftp_desc: 'Server dosyalarına erişim için FTP ayarları',
    setup_paths_title: 'Dosya Yolları',
    setup_paths_desc: 'Client ve Server dosya yolları',
    setup_complete_title: 'Tamamlandı',
    setup_complete_desc: 'Kurulum başarıyla tamamlandı',
    setup_complete_msg: 'Metin2 Dev Toolkit başarıyla yapılandırıldı.',
    setup_configured: 'Yapılandırılan Ayarlar:',
    setup_not_configured: 'Yapılandırılmadı',
    setup_finish: 'Tamamla',
    setup_next: 'İleri',
    setup_back: 'Geri',
    setup_test_db: 'Bağlantıyı Test Et',
    setup_test_ftp: 'FTP Bağlantısını Test Et',
    setup_validate_paths: 'Yolları Doğrula',
    setup_testing: 'Test Ediliyor...',
    setup_validating: 'Doğrulanıyor...',
    setup_db_success: 'Bağlantı Başarılı!',
    setup_ftp_success: 'FTP Bağlantısı Başarılı!',
    setup_paths_success: 'Yollar Doğrulandı!',
    setup_db_required: 'Devam etmek için veritabanı bağlantısını test edin.',
    setup_ftp_optional: 'FTP ayarları isteğe bağlıdır.',
    setup_paths_optional: 'Dosya yolları isteğe bağlıdır.',
    // TopBar
    game_server: 'Game Server',
    database: 'Database',
    players_online: 'Players Online',
    uptime: 'Uptime',
    online: 'Online',
    offline: 'Offline',
    notifications: 'Bildirimler',
    no_notifications: 'Bildirim yok',
    settings: 'Ayarlar',
    db_settings: 'Database Ayarları',
    ftp_settings: 'FTP Ayarları',
    path_settings: 'Dosya Yolları',
    theme_settings: 'Tema Ayarları',
    language_settings: 'Dil Ayarları',
    reset_settings: 'Ayarları Sıfırla',
    reset_confirm: 'Tüm ayarlar sıfırlanacak. Emin misiniz?',
    all_systems_ok: 'Tüm Sistemler Çalışıyor',
    system_issues: 'Sistem Sorunları Tespit Edildi',
    check_updates: 'Güncelleme Kontrol Et',
    // Dashboard
    welcome: 'Metin2 Dev Toolkit\'e Hoş Geldin!',
    welcome_sub: 'Private server geliştirme sürecini hızlandıran modern araçlar',
    active_projects: 'Aktif Projeler',
    total_items: 'Toplam Item',
    quest_count: 'Quest Sayısı',
    online_players: 'Online Oyuncu',
    recent_activity: 'Son Aktiviteler',
    open_module: 'Modülü Aç →',
    last_update: 'Son güncelleme',
    // Sidebar
    dashboard: 'Dashboard',
    shop_manager: 'Shop Manager',
    proto_editor: 'Proto Editor',
    quest_generator: 'Quest Generator',
    map_tool: 'Map Tool',
    ui_tools: 'UI Tools',
    log_analyzer: 'Log Analyzer',
    server_status: 'Server Status',
    // Shop Manager
    shops: 'Dükkanlar',
    connected: 'Bağlı',
    disconnected: 'Bağlantısız',
    search_shop: 'Dükkan ara...',
    select_shop: 'Dükkan Seçin',
    select_shop_desc: 'Düzenlemek için sol panelden bir dükkan seçin',
    hide_preview: 'Önizlemeyi Gizle',
    show_preview: 'Önizlemeyi Göster',
    save: 'Kaydet',
    loading: 'Yükleniyor...',
    item_added: 'Item eklendi!',
    item_removed: 'Item silindi!',
    shop_saved: 'Dükkan başarıyla kaydedildi!',
    no_db_connection: 'Database bağlantısı yok!',
    save_error: 'Kaydetme hatası: ',
    delete_error: 'Silme hatası: ',
    // NPC Editor
    npc_editor: 'NPC & Mount Editor',
    npc_editor_desc: 'npclist.txt dosyasını yönet',
    npc_code: 'NPC Kodu',
    npc_model: 'Model İsmi',
    add_npc: 'Yeni NPC Ekle',
    edit_npc: 'NPC Düzenle',
    delete_npc: 'Sil',
    edit: 'Düzenle',
    cancel: 'İptal',
    confirm_delete: 'Bu NPC\'yi silmek istediğinize emin misiniz?',
    npc_saved: 'NPC başarıyla kaydedildi!',
    npc_deleted: 'NPC silindi!',
    npc_file_not_set: 'Server yolu ayarlanmamış. Ayarlar\'dan server yolunu belirleyin.',
    search_npc: 'NPC ara...',
    no_npc_found: 'NPC bulunamadı',
    // Proto Editor
    proto_editor_title: 'Proto Editor',
    proto_editor_desc: 'Item ve Mob proto dosyalarını düzenle',
    item_proto: 'Item Proto',
    mob_proto: 'Mob Proto',
    load_file: 'Dosya Yükle',
    save_file: 'Dosyayı Kaydet',
    search_items: 'Item ara...',
    vnum: 'VNum',
    name: 'İsim',
    type: 'Tür',
    subtype: 'Alt Tür',
    size: 'Boyut',
    price: 'Fiyat',
    no_file_loaded: 'Dosya yüklenmedi',
    load_proto_hint: 'item_proto.txt veya mob_proto.txt dosyasını yükleyin',
    rows_loaded: 'satır yüklendi',
    // Quest Generator
    quest_gen_title: 'Quest Generator',
    quest_gen_desc: 'Lua quest dosyaları oluştur ve düzenle',
    quest_name: 'Quest Adı',
    quest_level: 'Minimum Seviye',
    quest_npc: 'NPC VNum',
    quest_type: 'Quest Türü',
    kill_quest: 'Kill Quest',
    delivery_quest: 'Delivery Quest',
    collection_quest: 'Collection Quest',
    mob_vnum: 'Mob VNum',
    kill_count: 'Öldürme Sayısı',
    reward_yang: 'Yang Ödülü',
    reward_exp: 'EXP Ödülü',
    generate_lua: 'Lua Kodu Üret',
    save_lua: 'Lua Dosyasını Kaydet',
    copy_code: 'Kodu Kopyala',
    copied: 'Kopyalandı!',
    // Map Tool
    map_tool_title: 'Map Tool',
    map_tool_desc: 'atlasinfo.txt dosyasını yönet',
    atlas_manager: 'AtlasInfo Yöneticisi',
    map_name: 'Harita Adı',
    x_coord: 'X Koordinatı',
    y_coord: 'Y Koordinatı',
    width: 'Genişlik',
    height: 'Yükseklik',
    add_map: 'Harita Ekle',
    teleport_code: 'Teleport Kodu',
    generate_teleport: 'Teleport Kodu Üret',
    search_map: 'Harita ara...',
    // Log Analyzer
    log_analyzer_title: 'Log Analyzer',
    log_analyzer_desc: 'Syslog ve syserr dosyalarını anlık takip et',
    live_log: 'Canlı Log Akışı',
    statistics: 'İstatistikler',
    filters: 'Filtreler',
    recent_errors: 'Son Hatalar',
    select_log_file: 'Log Dosyası Seç',
    watching: 'İzleniyor',
    stopped: 'Durduruldu',
    clear_logs: 'Temizle',
    // UI Tools
    ui_tools_title: 'UI Tools',
    ui_tools_desc: 'Sub dosyaları ve UI scriptlerini düzenle',
    sub_slicer: 'Sub Slicer',
    uiscript_editor: 'UIScript Editor',
    load_sub: '.sub Dosyası Yükle',
    load_script: 'Script Yükle',
    // Settings Modal
    host: 'Host',
    port: 'Port',
    username: 'Kullanıcı Adı',
    password: 'Şifre',
    db_name: 'Veritabanı Adı',
    server_path: 'Server Yolu',
    client_path: 'Client Yolu',
    locale: 'Dil/Locale',
    test_connection: 'Bağlantıyı Test Et',
    save_settings: 'Ayarları Kaydet',
    settings_saved: 'Ayarlar kaydedildi!',
    language: 'Dil',
    turkish: 'Türkçe',
    english: 'English',
    dark_theme: 'Koyu Tema',
    light_theme: 'Açık Tema',
    // Common
    error: 'Hata',
    success: 'Başarılı',
    warning: 'Uyarı',
    info: 'Bilgi',
    close: 'Kapat',
    confirm: 'Onayla',
    items: 'item',
    not_available: 'Mevcut değil',
    coming_soon: 'Yakında...',
  },
  en: {
    // Setup
    setup_title: 'Setup Wizard',
    setup_subtitle: 'Configure Metin2 Dev Toolkit',
    setup_db_title: 'MySQL Database',
    setup_db_desc: 'Metin2 database connection settings',
    setup_ftp_title: 'FTP Server',
    setup_ftp_desc: 'FTP settings for server file access',
    setup_paths_title: 'File Paths',
    setup_paths_desc: 'Client and Server file paths',
    setup_complete_title: 'Complete',
    setup_complete_desc: 'Setup completed successfully',
    setup_complete_msg: 'Metin2 Dev Toolkit has been configured successfully.',
    setup_configured: 'Configured Settings:',
    setup_not_configured: 'Not configured',
    setup_finish: 'Finish',
    setup_next: 'Next',
    setup_back: 'Back',
    setup_test_db: 'Test Connection',
    setup_test_ftp: 'Test FTP Connection',
    setup_validate_paths: 'Validate Paths',
    setup_testing: 'Testing...',
    setup_validating: 'Validating...',
    setup_db_success: 'Connection Successful!',
    setup_ftp_success: 'FTP Connection Successful!',
    setup_paths_success: 'Paths Validated!',
    setup_db_required: 'Please test the database connection to continue.',
    setup_ftp_optional: 'FTP settings are optional.',
    setup_paths_optional: 'File paths are optional.',
    // TopBar
    game_server: 'Game Server',
    database: 'Database',
    players_online: 'Players Online',
    uptime: 'Uptime',
    online: 'Online',
    offline: 'Offline',
    notifications: 'Notifications',
    no_notifications: 'No notifications',
    settings: 'Settings',
    db_settings: 'Database Settings',
    ftp_settings: 'FTP Settings',
    path_settings: 'File Paths',
    theme_settings: 'Theme Settings',
    language_settings: 'Language Settings',
    reset_settings: 'Reset Settings',
    reset_confirm: 'All settings will be reset. Are you sure?',
    all_systems_ok: 'All Systems Operational',
    system_issues: 'System Issues Detected',
    check_updates: 'Check for Updates',
    // Dashboard
    welcome: 'Welcome to Metin2 Dev Toolkit!',
    welcome_sub: 'Modern tools to accelerate private server development',
    active_projects: 'Active Projects',
    total_items: 'Total Items',
    quest_count: 'Quest Count',
    online_players: 'Online Players',
    recent_activity: 'Recent Activity',
    open_module: 'Open Module →',
    last_update: 'Last update',
    // Sidebar
    dashboard: 'Dashboard',
    shop_manager: 'Shop Manager',
    proto_editor: 'Proto Editor',
    quest_generator: 'Quest Generator',
    map_tool: 'Map Tool',
    ui_tools: 'UI Tools',
    log_analyzer: 'Log Analyzer',
    server_status: 'Server Status',
    // Shop Manager
    shops: 'Shops',
    connected: 'Connected',
    disconnected: 'Disconnected',
    search_shop: 'Search shop...',
    select_shop: 'Select a Shop',
    select_shop_desc: 'Select a shop from the left panel to edit',
    hide_preview: 'Hide Preview',
    show_preview: 'Show Preview',
    save: 'Save',
    loading: 'Loading...',
    item_added: 'Item added!',
    item_removed: 'Item removed!',
    shop_saved: 'Shop saved successfully!',
    no_db_connection: 'No database connection!',
    save_error: 'Save error: ',
    delete_error: 'Delete error: ',
    // NPC Editor
    npc_editor: 'NPC & Mount Editor',
    npc_editor_desc: 'Manage npclist.txt file',
    npc_code: 'NPC Code',
    npc_model: 'Model Name',
    add_npc: 'Add New NPC',
    edit_npc: 'Edit NPC',
    delete_npc: 'Delete',
    edit: 'Edit',
    cancel: 'Cancel',
    confirm_delete: 'Are you sure you want to delete this NPC?',
    npc_saved: 'NPC saved successfully!',
    npc_deleted: 'NPC deleted!',
    npc_file_not_set: 'Server path not set. Configure server path in Settings.',
    search_npc: 'Search NPC...',
    no_npc_found: 'No NPC found',
    // Proto Editor
    proto_editor_title: 'Proto Editor',
    proto_editor_desc: 'Edit Item and Mob proto files',
    item_proto: 'Item Proto',
    mob_proto: 'Mob Proto',
    load_file: 'Load File',
    save_file: 'Save File',
    search_items: 'Search items...',
    vnum: 'VNum',
    name: 'Name',
    type: 'Type',
    subtype: 'Subtype',
    size: 'Size',
    price: 'Price',
    no_file_loaded: 'No file loaded',
    load_proto_hint: 'Load item_proto.txt or mob_proto.txt file',
    rows_loaded: 'rows loaded',
    // Quest Generator
    quest_gen_title: 'Quest Generator',
    quest_gen_desc: 'Create and edit Lua quest files',
    quest_name: 'Quest Name',
    quest_level: 'Minimum Level',
    quest_npc: 'NPC VNum',
    quest_type: 'Quest Type',
    kill_quest: 'Kill Quest',
    delivery_quest: 'Delivery Quest',
    collection_quest: 'Collection Quest',
    mob_vnum: 'Mob VNum',
    kill_count: 'Kill Count',
    reward_yang: 'Yang Reward',
    reward_exp: 'EXP Reward',
    generate_lua: 'Generate Lua Code',
    save_lua: 'Save Lua File',
    copy_code: 'Copy Code',
    copied: 'Copied!',
    // Map Tool
    map_tool_title: 'Map Tool',
    map_tool_desc: 'Manage atlasinfo.txt file',
    atlas_manager: 'AtlasInfo Manager',
    map_name: 'Map Name',
    x_coord: 'X Coordinate',
    y_coord: 'Y Coordinate',
    width: 'Width',
    height: 'Height',
    add_map: 'Add Map',
    teleport_code: 'Teleport Code',
    generate_teleport: 'Generate Teleport Code',
    search_map: 'Search map...',
    // Log Analyzer
    log_analyzer_title: 'Log Analyzer',
    log_analyzer_desc: 'Monitor syslog and syserr files in real-time',
    live_log: 'Live Log Stream',
    statistics: 'Statistics',
    filters: 'Filters',
    recent_errors: 'Recent Errors',
    select_log_file: 'Select Log File',
    watching: 'Watching',
    stopped: 'Stopped',
    clear_logs: 'Clear',
    // UI Tools
    ui_tools_title: 'UI Tools',
    ui_tools_desc: 'Edit sub files and UI scripts',
    sub_slicer: 'Sub Slicer',
    uiscript_editor: 'UIScript Editor',
    load_sub: 'Load .sub File',
    load_script: 'Load Script',
    // Settings Modal
    host: 'Host',
    port: 'Port',
    username: 'Username',
    password: 'Password',
    db_name: 'Database Name',
    server_path: 'Server Path',
    client_path: 'Client Path',
    locale: 'Locale',
    test_connection: 'Test Connection',
    save_settings: 'Save Settings',
    settings_saved: 'Settings saved!',
    language: 'Language',
    turkish: 'Türkçe',
    english: 'English',
    dark_theme: 'Dark Theme',
    light_theme: 'Light Theme',
    // Common
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    close: 'Close',
    confirm: 'Confirm',
    items: 'items',
    not_available: 'Not available',
    coming_soon: 'Coming soon...',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      const saved = localStorage.getItem('metin2-lang');
      return saved || 'tr';
    } catch { return 'tr'; }
  });

  const setLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('metin2-lang', newLang);
  };

  const t = (key) => translations[lang][key] || translations['tr'][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
